
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import SyncUserWithConvex from "@/components/SyncUserWithConvex";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import CookieConsent from "@/components/CookieConsent";
import { Toaster } from "sonner";
import { CartProvider } from "@/components/cart/CartProvider";
import { CurrencyProvider } from "@/components/CurrencyContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <ClerkProvider
          publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!}
          appearance={{
            variables: {
              colorPrimary: "#3b82f6",
            },
          }}
        >
          
          <ConvexClientProvider>
            <CartProvider>
              <CurrencyProvider>
                <div className="min-h-screen flex flex-col">
                  <Header/>
                  <SyncUserWithConvex/>
                  <main className="flex-grow">
                    {children}
                  </main>
                  <CookieConsent/>
                  <Toaster/>
                </div>
              </CurrencyProvider>
            </CartProvider>
          </ConvexClientProvider>
        </ClerkProvider>
       
      </body>
    </html>
  );
}
